.gitignore, README.md, extract_creds.py, start.sh
Addresses issue #9 (https://github.com/RhinoSecurityLabs/cloudgoat/issues/9). Python3 officially works now
Added warning to README
Fixed an error in extract_creds.py with Glue disabled
=> Python3 support

terraform/ec2.tf
Fixes the bug here: https://twitter.com/rob_pwners/status/1029702172848660480
The policy for the EC2 instance profile role was inline, rather than customer managed.
=> EC2 instance profile policy fix

scenarios/rce_web_app/terraform/ec2.tf
During the install, an interactive prompt for OpenSSL would halt the install of the webserver. Adding this line will make sure interactive prompts do not halt the install. #50
=> Update ec2.tf in rce_web_app

scenarios/iam_privesc_by_rollback/terraform/iam.tf, scenarios/iam_privesc_by_rollback/terraform/outputs.tf
This is to match the other scenarios and allow running multiple copies of the same scenario in a single AWS account.
=> Use cgid in resource names for iam_privesc_by_rollback

scenarios/ecs_efs_attack/cheat_sheet.md
Fix typo in  ecs_efs_attack cheatsheet command to list the privileges(Point 3 in cheatsheet - scenarios/ecs_efs_attack/cheat_sheet.md )
Present command - aws iam list --profile ruse
Fixed command - aws iam list-policies --profile ruse
=> Typo fix in ecs_efs_attack cheatsheet command to list the privileges

core/python/python_terraform/__init__.py
The comparison check is backwards and break versions other than 0.15. This change fixes the comparison check.
=> Fixed version check for terraform destroy command.

scenarios/rce_web_app/cheat_sheet_lara.md
The SSH key pair generated for the RCE needs to have a public key that's short enough for the RCE. A long public key, such as an RSA public key generated with ssh-keygen, will get truncated in the RCE and cause the command to fail. Using an ed25519 key pair solves this issue.
=> Correction to Lara cheat sheet

cloudgoat.py, core/python/commands.py, core/python/python_terraform/__init__.py, core/python/tests.py
* Change the behavior of running create on an existing scenario. Previously this would destroy and create the deployment, this is problematic when you want to make minor changes to a scenario and isn't terribly useful in other cases (destroy + create can always be run separately).
* Fix help output when no commands are passed.
=> Help fixes + change create to always runs apply

scenarios/cloud_breach_s3/terraform/s3.tf, scenarios/ec2_ssrf/terraform/s3.tf, scenarios/rce_web_app/terraform/iam.tf, scenarios/rce_web_app/terraform/lb.tf, scenarios/rce_web_app/terraform/locals.tf, scenarios/rce_web_app/terraform/rds.tf, scenarios/rce_web_app/terraform/s3.tf
As described in #100, scenarios containing S3 buckets currently do not work because of an invalid underscore character in the S3 bucket names. This PR ensures that no such character exists and solves the issue
=> Ensure resource names (S3 bucket, RDS, load balancer) do not contain invalid characters (closes #98, #100)

scenarios/ec2_ssrf/terraform/iam.tf
This issue caused the EC2 SSRF scenario to be broken (tested on Terraform 0.14.x and 1.x). Introduced in 2b15402c8d35a267aa77c2d9d80c9952f4e706e6
=> Fix broken IAM policy in ec2_ssrf scenario

scenarios/ecs_efs_attack/cheat_sheet.md
Hi,
There was a missing step between registering task definition and waiting for task to run. The task will never run if the service was never updated with the new task definition. I have added the missing step and command to run.
=> Fix missing step in ecs_efs_attack cheat sheet.

scenarios/codebuild_secrets/terraform/lambda.tf, scenarios/ec2_ssrf/terraform/lambda.tf
Lambda 3.6 is no longer supported so the terraform apply fails. simple fix was to bump to 3.9
=> Updated the lambda python version in two scenarios 

scenarios/detection_evasion/terraform/cloudwatch.tf
There is a misconfiguration in the filter pattern for the instance_profile_abnormal_usage metric filter. The IP -> assumed role for the easy path is currently source_ip == easy_instance_ip && useridentity.arn == hard_path.name, which means that usage of the easy_path instance role outside of the instance will not trigger an alert. This PR adjusts the filter to source_ip == easy_instance_ip && useridentity.arn == easy_path.name.
=> detection_evasion: fixed filter pattern for instance profile usage

scenarios/vulnerable_lambda/README.md
Fix Typo in `README.md` on `vulnerable_lambda` scenario.
=> Fix Typo in README.md

scenarios/vulnerable_cognito/cheat_sheet.md, scenarios/vulnerable_cognito/manifest.yml, scenarios/vulnerable_cognito/terraform/apig.tf, scenarios/vulnerable_cognito/terraform/cognito.tf, scenarios/vulnerable_cognito/terraform/data_sources.tf, scenarios/vulnerable_cognito/terraform/lambda.tf, scenarios/vulnerable_cognito/terraform/outputs.tf, scenarios/vulnerable_cognito/terraform/provider.tf, scenarios/vulnerable_cognito/terraform/s3.tf, scenarios/vulnerable_cognito/terraform/variables.tf, scenarios/vulnerable_cognito/terraform/versions.tf
- Pulling in additional cheat sheet steps from https://github.com/RhinoSecurityLabs/cloudgoat/pull/204
- Deprecated resource `aws_s3_bucket_object-> aws_s3_object`
- Remove `template_file` data call, switched to `templatefile()` function
- Add `aws_s3_bucket_public_access_block` resource to allow the bucket policy (https://github.com/RhinoSecurityLabs/cloudgoat/issues/187)
- Formatting of Terraform code (`terraform fmt`)
- Linting (used [tflint](https://github.com/terraform-linters/tflint))
- Switched from json blobs to Terraform `jsonencode`
- Move inline policies directly onto the role
- Remove unused commented out Terraform
Run thought the scenario in Terraform versions `1.2.0` & `1.5.6` (latest)
=> Update Vulnerable Cognito

scenarios/detection_evasion/README.md, scenarios/detection_evasion/cheat_sheet.md, scenarios/detection_evasion/terraform/cloudtrail.tf, scenarios/detection_evasion/terraform/cloudwatch.tf, scenarios/detection_evasion/terraform/data_sources.tf, scenarios/detection_evasion/terraform/ec2.tf, scenarios/detection_evasion/terraform/iam.tf, scenarios/detection_evasion/terraform/outputs.tf, scenarios/detection_evasion/terraform/provider.tf, scenarios/detection_evasion/terraform/secrets_manager.tf, scenarios/detection_evasion/terraform/variables.tf, scenarios/detection_evasion/terraform/vpc.tf
- Add internet gateway to VPC, the easy server could not communicate with the public internet
- Hard still cannot talk to internet/secretmanager (no route)
- Add subnet Ids on easy EC2 instance
- Error (`VPCIdNotSpecified: No default VPC for this user`)
- Pull the EC2 AMI dynamically, will work in other regions
- linting
- formatting (`terraform fmt`)
Tested with Terraform `1.5.6`
=> Fix Detection Evasion Scenario

scenarios/cicd/terraform/dev_machine.tf, scenarios/cicd/terraform/sdlc.tf
- ECR repository will be deleted even with images
- https://github.com/RhinoSecurityLabs/cloudgoat/issues/200
- Add egress security group on EC2 instance to allow communication with SSM
- https://github.com/RhinoSecurityLabs/cloudgoat/issues/212
- https://github.com/RhinoSecurityLabs/cloudgoat/issues/200
- Verify SSM works by default
- ECR removes with images
=> Fixing Issues with ECR Removal & SSM Connectivity

scenarios/ecs_takeover/terraform/ec2.tf
- Require the image to be `x86_64`
- https://github.com/RhinoSecurityLabs/cloudgoat/issues/209
- https://github.com/RhinoSecurityLabs/cloudgoat/issues/205
Terraform `1.5.6`
=> ECS Takeover | x86_64 AMI

scenarios/codebuild_secrets/terraform/rds.tf
- Update from PostgreSQL `13.7 -> 16.2` 
- 13.7 is now outdated and not supported by AWS
```
Error: creating RDS DB Instance (cg-rds-instance-codebuild-secrets-cgidutxr0a5lqu): InvalidParameterCombination: Cannot find version 
13.7 for postgres
```
Ran through the scenario and confirmed that flags are still populated by the EC2 user-data script.
Planning to go back through this scenario later and refactor the Terraform
=> Updated codebuild-secrets RDS to 16.2

.gitignore, README.md, requirements.txt
- Recommend using python virtual environments
- Git ignore the `.venv` directory
- Updated python packages to latest versions
Locally running scenarios (including ecs_takeover)
Without setting up virtual environments the following error is raised.
```
❯ pip3 install -r ./requirements.txt
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
xyz, where xyz is the package you are trying to
install.
If you wish to install a non-brew-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip.
If you wish to install a non-brew packaged Python application,
it may be easiest to use pipx install xyz, which will manage a …
```
=> Recommend Python Virtual Environment & Update Modules

cloudgoat.py
- What was changed
Was this tested with different Terraform versions?
=> resolves terraform version error

README.md
```
./cloudgoat.py create
```
and not
```
./cloudgoat.py Create
```
Fix typo upper case
=> As the command runs with lowercase

Dockerfile, requirements.txt
- Updated Dockerfile and requirements.txt
The current Dockerfile was not working as is anymore (tested on Kali Linux 2024.4), it always showed this error message during the building process.
So, I updated the files to fix dependency issues.
I tested it and it works fine after my changes.
I did not change the files to the latest version of the software in order to avoid having any bugs, so, I chose some versions that are more recent, have security fixes and are stable enough.
=> Updated Dockerfile and requirements.txt

scenarios/beanstalk_secrets/README.md, scenarios/beanstalk_secrets/cheat_sheet.md, scenarios/beanstalk_secrets/manifest.yml, scenarios/beanstalk_secrets/terraform/ec2.tf, scenarios/beanstalk_secrets/terraform/iam.tf, scenarios/beanstalk_secrets/terraform/output.tf, scenarios/beanstalk_secrets/terraform/provider.tf, scenarios/beanstalk_secrets/terraform/secrets.tf, scenarios/beanstalk_secrets/terraform/variables.tf, scenarios/beanstalk_secrets/terraform/vpc.tf
**Description:**
This PR adds a new CloudGoat scenario called **beanstalk_secrets**. The scenario simulates a real-world AWS misconfiguration in Elastic Beanstalk that I have seen while pentesting. 
**New Pacu Module:**
This scenario is designed to showcase a new Pacu module for Elastic Beanstalk Enumeration. This module is currently pending review and has been submitted as a Pull Request at [https://github.com/RhinoSecurityLabs/pacu/pull/469](https://github.com/RhinoSecurityLabs/pacu/pull/469).
**Additional Notes:**
- Users must manually delete the additional access keys created for the admin user to clean up the environment.
=> New Scenario: Beanstalk Secrets

cloudgoat/scenarios/aws/beanstalk_secrets/terraform/ec2.tf
I have a very minor update to the name regex for the Beanstalk Secrets scenario. A user on Discord reported an error that the scenario wouldn't launch in their region. This is due to it pulling too new of a version of Python and it not matching the OS available. 
The updated regex resolves this issue.
=> Update Name Regex in beanstalk_secrets terraform

cloudgoat/scenarios/aws/sns_secrets/terraform/api_gateway.tf
This PR resolves [Issue #371](https://github.com/RhinoSecurityLabs/cloudgoat/issues/371), which was caused by the removal of the stage_name argument from the aws_api_gateway_deployment resource in Terraform AWS Provider v4+.
=> Fix sns_secrets scenario
