RhinoSecurityLabs/cloudgoat

README.md
start.sh

Addresses https://github.com/RhinoSecurityLabs/cloudgoat/issues/10

fixed random string generation to support Mac

---

README.md
terraform/bob.tf

Resolves a problem with Bob not being able to fully exploit his scenario without some bruteforcing or cheating.

Bob update

---

README.md

Add a warning for AWS creds mount

---

scenarios/ec2_ssrf/terraform/ec2.tf
scenarios/ec2_ssrf/terraform/iam.tf

Also added cloudwatch permissions to IAM role
in ec2_ssrf so we can use pacu to download from
the bucket.

Added cgid in resources for ec2_ssrf

---

scenarios/lambda_privesc/manifest.yml

Hi, I have a small request to change my name to include my organization. Thanks!

Update author's name in lambda_privesc scenario

---

scenarios/ecs_efs_attack/README.md

Fixed some spelling and grammar issues.

Fix for spelling and grammar issues in README.md

---

scenarios/cicd/README.md

Some TODOs were left behind from #116

Update README for CI/CD scenario

---

scenarios/vulnerable_lambda/manifest.yml

Python PyYaml library shows error while trying to parse the manifest file in the vulnerable lambda scenario. Update the file so the error doesn't occur again.

Update vulnerable_lambda manifest.yaml file

---

scenarios/codebuild_secrets/README.md
scenarios/codebuild_secrets/terraform/rds.tf

- Change database name argument
- https://github.com/RhinoSecurityLabs/cloudgoat/issues/199
- Update readme

Bugfix CodeBuild Secrets

---

README.md
core/terraform/example-scenario/terraform/outputs.tf
core/terraform/example-scenario/terraform/provider.tf
core/terraform/example-scenario/terraform/variables.tf

- Adding types to the variables
- Specify minimum Terraform & provider versions
- Add provider to use the profile & region passed in
- Formatting
N/A

Update example scenario

---

README.md

- Added a summary of the two scenarios(sqs_flag_shop, rds_snapshot) to README.md

Flagshop and rds snapshot add summary

---

scenarios/lambda_privesc/README.md
scenarios/lambda_privesc/cheat_sheet_chris.md
scenarios/lambda_privesc/manifest.yml
scenarios/lambda_privesc/terraform/data_sources.tf
scenarios/lambda_privesc/terraform/iam.tf
scenarios/lambda_privesc/terraform/outputs.tf
scenarios/lambda_privesc/terraform/provider.tf
scenarios/lambda_privesc/terraform/variables.tf

- Refactor the code
- Formatting, linting, cleanup
- Updating cheat sheet
- Explain the steps a little more
Launched the scenario and looked through the policies to confirm that they are still valid

Refactor Lambda Privesc

---

scenarios/codebuild_secrets/terraform/iam.tf

- Prevents the restoration of the RDS snapshot
- [Discord issue](https://discord.com/channels/969671994599669760/1074135870753488906/1238144664331092122)
None

Updated codebuild secrets iam permissions to allow tagging rds resource

---

scenarios/iam_privesc_by_attachment/manifest.yml
scenarios/iam_privesc_by_attachment/terraform/data_sources.tf
scenarios/iam_privesc_by_attachment/terraform/ec2.tf
scenarios/iam_privesc_by_attachment/terraform/iam.tf
scenarios/iam_privesc_by_attachment/terraform/iam_meek.tf
scenarios/iam_privesc_by_attachment/terraform/iam_mighty.tf
scenarios/iam_privesc_by_attachment/terraform/local.tf
scenarios/iam_privesc_by_attachment/terraform/outputs.tf
scenarios/iam_privesc_by_attachment/terraform/provider.tf
scenarios/iam_privesc_by_attachment/terraform/variables.tf
scenarios/iam_privesc_by_attachment/terraform/vpc.tf

- Implement the fix from https://github.com/RhinoSecurityLabs/cloudgoat/issues/183
- Cleaning up the Terraform
- Formatting, use of jsonencod & readability
- Combined the two security groups
Ran through the scenario

Refactor IAM Privesc by Attachment

---

scenarios/rds_snapshot/terraform/vpc.tf

- This pull request fixes the RDS Snapshot Scenario's Database Whitelist

Fix RDS Snapshot Scenario Database Whitelist 

---

scenarios/sqs_flag_shop/assets/init_rds.tpl
scenarios/sqs_flag_shop/cheat_sheet.md
scenarios/sqs_flag_shop/manifest.yml
scenarios/sqs_flag_shop/terraform/cloudwatch.tf
scenarios/sqs_flag_shop/terraform/data.tf
scenarios/sqs_flag_shop/terraform/ec2.tf
scenarios/sqs_flag_shop/terraform/iam.tf
scenarios/sqs_flag_shop/terraform/lambda.tf
scenarios/sqs_flag_shop/terraform/output.tf
scenarios/sqs_flag_shop/terraform/provider.tf
scenarios/sqs_flag_shop/terraform/rds.tf
scenarios/sqs_flag_shop/terraform/security_groups.tf
scenarios/sqs_flag_shop/terraform/source/flask/templates/index.html
scenarios/sqs_flag_shop/terraform/source/initialize_database.sql
scenarios/sqs_flag_shop/terraform/source/lambda_function.py
scenarios/sqs_flag_shop/terraform/sqs.tf
scenarios/sqs_flag_shop/terraform/variables.tf
scenarios/sqs_flag_shop/terraform/vpc.tf

- Remove unused data calls that were brought up [here](https://github.com/RhinoSecurityLabs/cloudgoat/pull/276#pullrequestreview-2410682441)
- Update all Terraform naming to be standardized
- Switch to a default tags block
- Update flag
- Move lambda and sql into source directory
Deployed with a newer version of Terraform (1.9.2)
Confirmed scenario plays out as intended

Update SQS Flag Shop Terraform

---

scenarios/iam_privesc_by_key_rotation/terraform/outputs.tf

- Correct the output name, was a ctrl+c. ctrl+v from another scenario

Correct iam_privesc_by_key_rotation Terraform Output Name

---

scenarios/iam_privesc_by_key_rotation/cheat_sheet.md
scenarios/iam_privesc_by_rollback/cheat_sheet_raynor.md

- I added the command **aws sts get-caller-identity** --profile raynor so we can find the username of raynor
- I also changed the labels on the **--user-name** and **--policy-arn** arguments so that we know what value we need to put in each argument.

Edit iam privesc by rollback cheat sheet

---

scenarios/ecs_takeover/terraform/website/assets/index.html

This makes it easier to see the commands.
This first image shows the original:
This second image shows what merging the pull request would look like.

Change text input into textarea

---

scenarios/scenario_template/README.md
scenarios/scenario_template/cheat_sheet.md
scenarios/scenario_template/terraform/ec2.tf
scenarios/scenario_template/terraform/iam.tf
scenarios/scenario_template/terraform/output.tf
scenarios/scenario_template/terraform/provider.tf
scenarios/scenario_template/terraform/variables.tf
scenarios/scenario_template/terraform/vpc.tf

- Update template formatting to be consistent with modern scenarios
- Specify size & difficulty
Tested with Terraform v1.9.2

Update Template Scenario Formatting

---

README.md

This PR updates the scenarios page to improve organization and clarity by grouping scenarios by difficulty. The main changes include:
- **Grouped by Difficulty:** The scenarios are now organized into three collapsible sections: **Easy**, **Medium**, and **Hard**.
- **Default Behavior:** The "Easy" category is expanded by default, while the "Medium" and "Hard" sections are collapsed until the user expands them.
- **Simplified Titles:** Removed the size labels (e.g., "Small", "Large") from the scenario names to reduce confusion and streamline the display.
These improvements should make it easier for users to navigate and identify the scenarios they are interested in.

Update Scenarios Page Grouping and UI Enhancements

---

README.md

Removed links to contributor URLs to prevent potential abuse in the future

Remove Contributor URLs 

---

.github/workflows/docker-terraform-compatibility.yaml
.github/workflows/scenario-terraform-compatibility.yaml

Added 2 new workflows:
- When a new scenario is created, or an existing one is modified, the scenario is tested by `terraform validate` and `terraform plan`. Can test multiple terraform versions in parallel.
- When the Dockerfile is modified, detect the terraform version and test every scenario with `terraform validate` and `terraform plan`.
Successful execution of the workflows can be seen on my fork:
- https://github.com/nobodynate/cloudgoat/actions/runs/13837052581
- https://github.com/nobodynate/cloudgoat/actions/runs/13836972263

added workflows for terraform validation

---

cloudgoat/scenarios/lambda_privesc/cheat_sheet_chris.md

- Re-wrote the full walkthrough. Added significantly more details and explanations so those new to AWS can follow along without being lost.

Lambda privesc walkthrough rewrite

---

cloudgoat/scenarios/iam_privesc_by_rollback/cheat_sheet_raynor.md

- The current walkthrough is already quite good. I updated language and explanations so it's easier for beginners to understand what is going on.

Privesc by rollback walkthrough update

---

cloudgoat/cloudgoat.py

Fix for #323
Make --profile arg store as a string

Fixes #324

---

.github/workflows/scenario-terraform-compatibility.yaml

fix_action_find_scenario_command

---

.github/workflows/scenario-terraform-compatibility.yaml

- Fixed the scenario validation action.
Tested in my fork. Worked for AWS and Azure

Fixed action. Only runs on new or modified scenararios

---

.github/workflows/scenario-terraform-compatibility.yaml

- Was only working for modified scenarios. Updated Terraform validation to checkout the PR so it can find the scenario folder if the scenario is new (only exists on the PR).
Tested with a new scenario in my fork.

need to checkout the PR

---

cloudgoat/scenarios/aws/beanstalk_secrets/terraform/ec2.tf

- Updated the solution stack to 64bit Amazon Linux 2023 v4.5.0 running Python 3.13 to fix issues with launching the scenario

Updated solution stack for Beanstalk

---

cloudgoat/scenarios/aws/beanstalk_secrets/terraform/ec2.tf

- Updates the EC2 to fix a version bug 
- I need to make this dynamic as well

Fixed beanstalk ec2

---

cloudgoat/scenarios/aws/beanstalk_secrets/terraform/ec2.tf

- Updated the ec2.tf file for Beanstalk Secrets
- It now grabs the Solution Stack dynamically rather than being hardcoded 
- This prevents future issue when solution stacks are depreciated by AWS

Updated Beanstalk Secrets to dynamically grab the correct solution stack

---

.github/workflows/docker-terraform-compatibility.yaml

- Updated the action to use pull_request instead of pull_request_target.
Tested in my fork. All checks passed.

changed docker validation action trigger to pull_request

---

cloudgoat/scenarios/aws/iam_privesc_by_ec2/README.md
cloudgoat/scenarios/aws/iam_privesc_by_ec2/cheat_sheet_dev_user.md
cloudgoat/scenarios/aws/iam_privesc_by_ec2/manifest.yml
cloudgoat/scenarios/aws/iam_privesc_by_ec2/terraform/data.tf
cloudgoat/scenarios/aws/iam_privesc_by_ec2/terraform/data_sources.tf
cloudgoat/scenarios/aws/iam_privesc_by_ec2/terraform/ec2.tf
cloudgoat/scenarios/aws/iam_privesc_by_ec2/terraform/iam.tf
cloudgoat/scenarios/aws/iam_privesc_by_ec2/terraform/outputs.tf
cloudgoat/scenarios/aws/iam_privesc_by_ec2/terraform/provider.tf
cloudgoat/scenarios/aws/iam_privesc_by_ec2/terraform/variables.tf
cloudgoat/scenarios/aws/iam_privesc_by_ec2/terraform/vpc.tf

- Fixed the reference the the IAM role being incorrect (was giving the name not the arn)
- Corrected cheat sheet with modify user-data command
- Updated description on what completion of the scenario is. You cannot actually exfil data from the ec2 since it does not have any ingress/egress access.
- Cleaned up Terraform & moved to data call for ec2 ami
Tested on 1.5.0

Bugfixes, refactor and rename
